CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE chiral.reminder
(
	Id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	Body VARCHAR NOT NULL,
	Timestamp VARCHAR NOT NULL,
	CreatedUserId VARCHAR(25) NULL,
	CreatedServerId VARCHAR(25) NULL,
	Active BOOLEAN NOT NULL DEFAULT (TRUE),
	DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)