CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE chiral.reminder
(
	Id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	Value VARCHAR(100) NOT NULL,
	CreatedUserId VARCHAR(100) NULL,
	CreatedServerId VARCHAR(100) NULL,
	Active BOOLEAN NOT NULL DEFAULT (TRUE),
	DateCreated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DateModified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)